//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.Composition;
using System.Windows.Data;
using Qube7.Composite.Presentation;

namespace Module1.Controllers.Startup
{
    public partial class StylesDemoViewModel
    {
        [System.Diagnostics.DebuggerNonUserCodeAttribute]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public partial class CommandAggregator
        {
            /// <summary>
            /// Gets the Navigate command.
            /// </summary>
            public Qube7.Composite.Presentation.Command Navigate
            {
                get;
                private set;
            }

            partial void Initialize(StylesDemoViewModel model)
            {
                Navigate = Qube7.Composite.Presentation.Command.Create(new System.Action<object>(model.ExecuteNavigateCommand), new System.Func<object, bool>(model.CanExecuteNavigateCommand));
            }
        }
    }
}
