//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.Composition;
using Qube7.Composite.Presentation;

namespace $safeprojectname$.Controllers.Startup
{
    public partial class HelloWorldViewModel
    {
        [System.Diagnostics.DebuggerNonUserCodeAttribute]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
        public partial class CommandAggregator
        {
            /// <summary>
            /// Gets the Hello command.
            /// </summary>
            public Qube7.Composite.Presentation.DelegateCommand<object> Hello { get; private set; }

            partial void Initialize(HelloWorldViewModel model)
            {
                Hello = new Qube7.Composite.Presentation.DelegateCommand<object>(new System.Action<object>(model.ExecuteHelloCommand), new System.Func<object, bool>(model.CanExecuteHelloCommand), nameof(Hello));
            }

            partial void Aggregate(System.Collections.Generic.ICollection<System.Windows.Input.ICommand> commands)
            {
                commands.Add(Hello);
            }
        }
    }
}
