//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qube7.Composite {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Qube7.Composite.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While examining an assembly, expected an assembly with a certain identity but found a different one instead. Assembly file: &apos;{0}&apos;, assembly identity expected: &apos;{1}&apos;, found: &apos;{2}&apos;..
        /// </summary>
        internal static string AssemblyNameMismatch {
            get {
                return ResourceManager.GetString("AssemblyNameMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection change notification must provide the index at which the change occurred..
        /// </summary>
        internal static string ChangeIndexExpected {
            get {
                return ResourceManager.GetString("ChangeIndexExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update the collection while the navigation is in progress..
        /// </summary>
        internal static string CollectionNavigating {
            get {
                return ResourceManager.GetString("CollectionNavigating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update the collection while the recomposition is in progress..
        /// </summary>
        internal static string CollectionRecomposing {
            get {
                return ResourceManager.GetString("CollectionRecomposing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The composition container encountered an unexpected exception while disposing, review inner exception for details..
        /// </summary>
        internal static string ContainerDisposeException {
            get {
                return ResourceManager.GetString("ContainerDisposeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The controller has already associated composition container and is activated..
        /// </summary>
        internal static string ControllerActivated {
            get {
                return ResourceManager.GetString("ControllerActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; can be used at design-time only..
        /// </summary>
        internal static string DesignTimeOnly {
            get {
                return ResourceManager.GetString("DesignTimeOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; type must be concrete type, assignable to the &apos;{1}&apos; type, that has public parameterless constructor..
        /// </summary>
        internal static string ModuleTypeInvalid {
            get {
                return ResourceManager.GetString("ModuleTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must be of the &apos;{0}&apos; type..
        /// </summary>
        internal static string ParameterTypeInvalid {
            get {
                return ResourceManager.GetString("ParameterTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent controller does not have associated composition container. Make sure that the parent controller is activated before activating child controller..
        /// </summary>
        internal static string ParentNotActivated {
            get {
                return ResourceManager.GetString("ParentNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only &apos;{0}&apos; instance property expression is supported..
        /// </summary>
        internal static string PropertyExpressionInvalid {
            get {
                return ResourceManager.GetString("PropertyExpressionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; property not found on the &apos;{1}&apos; object..
        /// </summary>
        internal static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range actions are not supported..
        /// </summary>
        internal static string RangeAction {
            get {
                return ResourceManager.GetString("RangeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource must have a name to resolve..
        /// </summary>
        internal static string ResourceNameExpected {
            get {
                return ResourceManager.GetString("ResourceNameExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The style intended for type &apos;{0}&apos; cannot be applied to type &apos;{1}&apos;..
        /// </summary>
        internal static string StyleTypeInvalid {
            get {
                return ResourceManager.GetString("StyleTypeInvalid", resourceCulture);
            }
        }
    }
}
