//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qube7.Composite.Design {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Qube7.Composite.Design.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the {0} command..
        /// </summary>
        internal static string CommandPropertySummary {
            get {
                return ResourceManager.GetString("CommandPropertySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////     Runtime Version:{0}
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------.
        /// </summary>
        internal static string FileHeader {
            get {
                return ResourceManager.GetString("FileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to generate class name for the &apos;{0}&apos; file..
        /// </summary>
        internal static string InvalidClassIdentifier {
            get {
                return ResourceManager.GetString("InvalidClassIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to generate property name for the &apos;{0}&apos; resource..
        /// </summary>
        internal static string InvalidPropertyIdentifier {
            get {
                return ResourceManager.GetString("InvalidPropertyIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command generator does not support overloaded methods: &apos;{0}&apos;, omitting generation of the &apos;{1}&apos; command..
        /// </summary>
        internal static string MethodOverload {
            get {
                return ResourceManager.GetString("MethodOverload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names of the parameters of the &apos;{0}&apos; and &apos;{1}&apos; methods must match, omitting generation of the &apos;{2}&apos; command..
        /// </summary>
        internal static string ParameterNameMismatch {
            get {
                return ResourceManager.GetString("ParameterNameMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types of the parameters of the &apos;{0}&apos; and &apos;{1}&apos; methods must match, omitting generation of the &apos;{2}&apos; command..
        /// </summary>
        internal static string ParameterTypeMismatch {
            get {
                return ResourceManager.GetString("ParameterTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides access to the local resources of the outer type..
        /// </summary>
        internal static string ResourcesClassSummary {
            get {
                return ResourceManager.GetString("ResourcesClassSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks up a localized string similar to {0}..
        /// </summary>
        internal static string ResourcesPropertySummary {
            get {
                return ResourceManager.GetString("ResourcesPropertySummary", resourceCulture);
            }
        }
    }
}
